theme: next
# Site settings
title: YH Blog    				  	#ä½ åšå®¢çš„æ ‡é¢˜
SEOTitle: YH'sçš„åšå®¢ | You Blog    	 #æ˜¾ç¤ºåœ¨æµè§ˆå™¨ä¸Šæœç´¢çš„æ—¶å€™æ˜¾ç¤ºçš„æ ‡é¢˜
header-img: img/post-bg-rwd.jpg  	#æ˜¾ç¤ºåœ¨é¦–é¡µçš„èƒŒæ™¯å›¾ç‰‡
email: YH@gmail.com	
description: "çœŸæ£’ğŸ‘"  			 #ç½‘ç«™ä»‹ç»
keyword: "H5 Css3 JavaScript" #å…³é”®è¯
url: "https://yh.github.io"          # è¿™ä¸ªå°±æ˜¯å¡«å†™ä½ çš„åšå®¢åœ°å€
baseurl: ""      # è¿™ä¸ªæˆ‘ä»¬ä¸ç”¨å¡«å†™
language: zh-Hans


# Sidebar settings
sidebar: true                           # æ˜¯å¦å¼€å¯ä¾§è¾¹æ .
sidebar-about-description: "è¯´ç‚¹è£…é€¼çš„è¯ã€‚ã€‚ã€‚"
sidebar-avatar:/img/avatar-by.JPG      # ä½ çš„ä¸ªäººå¤´åƒ è¿™é‡Œä½ å¯ä»¥æ”¹æˆæˆ‘åœ¨imgæ–‡ä»¶å¤¹ä¸­çš„ä¸¤å¼ å¤‡ç”¨ç…§ç‰‡ img/avatar-m æˆ– avatar-g



# SNS settings
RSS: false
weibo_username:     username
zhihu_username:     username
github_username:    username
facebook_username:  username
jianshu_username:	jianshu_id


deploy:
    type: git # ä½¿ç”¨ Git æäº¤
    repository: https://github.com/13810874921/yh.github.io.git # å°±æ˜¯å­˜æ”¾åšå®¢çš„ä»“åº“åœ°å€